# Generated by Django 5.2.7 on 2025-11-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_service_account',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['external_id'], name='users_userp_externa_2345f7_idx'),
        ),
    ]
